config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "processos#home"

  resources :dashboards, only: ['index']

  get 'relatorios/gerar_relatorio', to: 'relatorios#gerar_relatorio', as: :gerar_relatorio

  resources :relatorios, only: [] do
    collection do
      get :setores
      get :processos
    end
  end

  resources :processos do
    resources :riscos, only: ['new', 'create']
  end

  resources :riscos, only: ['index', 'show', 'edit', 'update', 'destroy'] do
		resources :controles, only: ['new', 'create']
  end

  resources :controles, only: ['index', 'show', 'edit', 'update', 'destroy']
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form_controle.html.erb
<%= simple_form_for [risco, controle], remote: true do |f| %>
  <%= f.input :nome, label: "Nome do Controle" %>
  <%= f.input :novo_ou_modificado, as: :select, collection: novo_ou_modificado, label: "Controle Novo ou Modificado?" %>
  <%= f.input :tipo_do_controle, as: :select, collection: tipo_do_controle, label: "Tipo do Controle" %>
  <%= f.input :natureza_do_controle, as: :select, collection: natureza_do_controle, label: "Natureza do Controle" %>
  <%= f.input :relacao_com_o_risco, as: :select, collection: relacao_com_o_risco, label: "Relação com o Risco" %>
  <%= f.input :responsavel_pela_acao, label: "Responsável pela Ação" %>
  <%= f.input :data_prevista_de_inicio, as: :string, label: "Data Prevista de Início", input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :data_prevista_de_conclusao, as: :string, label: "Data Prevista de Conclusão", input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :data_real_de_conclusao, as: :string, label: "Data Real de Conclusão", input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :orgaos_setores_envolvidos, label: "Órgãos e Setores Envolvidos" %>
  <%= f.input :analise_EGR, label: "Análise EGR" %>
  <%= f.button :submit, controle.persisted? ? "Atualizar Controle" : "Criar Novo Controle", class: "btn btn-primary" %>
<% end %>

app/views/shared/_form_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/shared/_form_processo.html.erb
<%= simple_form_for processo, remote: true do |f| %>
  <%= f.input :nome %>
  <%= f.input :orgao %>
  <%= f.input :setor %>
  <%= f.input :gestor_processo %>
  <%= f.input :servidor_responsavel %>
  <%= f.input :objetivo_estrategico %>
  <%= f.input :embasamento_legal %>
  <%= f.input :sistemas_utilizados %>
  <%= f.input :partes_interessadas %>
  <hr class="my-4">
  <%= f.button :submit, processo.persisted? ? "Atualizar Processo" : "Criar Novo Processo", class: "btn btn-primary" %>
<% end %>

app/views/shared/_form_risco.html.erb
<%= simple_form_for [processo, risco], remote: true do |f| %>
  <%= f.input :nome, label: "Nome do Risco" %>
  <div data-controller="data-max-implantacao">
    <%= f.input :data_identificacao, as: :string, label: "Data de Identificação", input_html: { data: { controller: "datepicker", data_max_implantacao_target: "dataDeCadastro" } } %>
    <%= f.input :tipo_de_risco, as: :select, collection: tipo_de_risco, label: "Tipo de Risco" %>
    <%= f.input :associacao_risco, as: :select, collection: associacao_risco, label: "Associação do Risco" %>
    <%= f.input :causas, label: "Causas" %>
    <%= f.input :consequencias, label: "Consequências" %>
    <%= f.input :dimensoes_risco, as: :select, collection: dimensoes_risco, label: "Dimensões do Risco" %>
    <div data-controller="risco-inerente risco-residual">
      <%= f.input :probabilidade, as: :select, collection: probabilidade, label: "Probabilidade (Frequência)", input_html: { data: { risco_inerente_target: "probabilidade", action: "change->risco-inerente#calculateInerente" } } %>
      <%= f.input :justificativa_pr, label: "Justificativa da Probabilidade (Frequência)" %>
      <%= f.input :impacto, as: :select, collection: impacto, label: "Impacto", input_html: { data: { risco_inerente_target: "impacto", action: "change->risco-inerente#calculateInerente" } } %>
      <%= f.input :justificativa_imp, label: "Justificativa do Impacto" %>
      <%= f.input :risco_inerente, as: :string, label: "Risco Inerente", input_html: { readonly: true, data: { risco_inerente_target: "riscoInerente", action: "change->risco-residual#calculateResidual" } } %>
      <div data-controller="checkbox-controles-existentes fac procedimento-controle">
        <%= f.input :existe_procedimento_de_controle, label: "Existe Procedimento de Controle?", input_html: { data: { procedimento_controle_target: "existeControles", action: "change->procedimento-controle#habilitarCheckboxes" } } %>
        <%= f.input :descricao_do_controle_existente, label: "Descrição do Controle Existente" %>
        <%= f.input :controle_eficaz, label: "O Controle é Eficaz?", input_html: { disabled: true, data: { action: "click->checkbox-controles-existentes#enable change->fac#calculateFac", checkbox_controles_existentes_target: "checkboxMaster", fac_target: "checkbox", procedimento_controle_target: "checkEficaz" } } %>
        <%= f.input :controle_proporcional, label: "O Controle é Proporcional", input_html: { disabled: true, data: { checkbox_controles_existentes_target: "checkbox", fac_target: "checkbox", action: "change->fac#calculateFac" } } %>
        <%= f.input :controle_razoavel, label: "O Controle é Razoável", input_html: { disabled: true, data: { checkbox_controles_existentes_target: "checkbox", fac_target: "checkbox", action: "change->fac#calculateFac" } } %>
        <%= f.input :controle_adequado, label: "O Controle é Adequado", input_html: { disabled: true, data: { checkbox_controles_existentes_target: "checkbox", fac_target: "checkbox", action: "change->fac#calculateFac" } } %>
        <%= f.input :fator_de_avaliacao_controles, as: :string, label: "Fator de Avaliação dos Controles - FAC", input_html: { readonly: true, data: { fac_target: "fac", action: "change->risco-residual#calculateResidual" } } %>
      </div>
      <%= f.input :risco_residual, as: :string, label: "Risco Residual", input_html: { readonly: true, data: { risco_residual_target: "riscoResidual", data_max_implantacao_target: "residualDataMax", action: "change->data-max-implantacao#calculateData" } } %>
    </div>
    <%= f.input :resposta_sugerida_para_risco, as: :select, collection: resposta_sugerida_para_risco, label: "Resposta Sugerida para o Risco" %>
    <%= f.input :data_maxima_para_implantacao_dos_controles_propostos, as: :string, label: "Data Máxima para Implantação dos Controles Propostos", input_html: { readonly: true, data: { controller: "datepicker", data_max_implantacao_target: "dataMaxImplantacao" } } %>
  </div>
  <%= f.input :relacao_com_LGPD, label: "Tem Relação com a LGPD?" %>
  <%= f.button :submit, risco.persisted? ? "Atualizar Risco" : "Criar Novo Risco", class: "btn btn-primary" %>
<% end %>

app/views/shared/_modal_controle.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" data-controller="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" inert>
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "shared/form_controle", risco: @risco, controle: @controle, novo_ou_modificado: @novo_ou_modificado,
            tipo_do_controle: @tipo_do_controle, natureza_do_controle: @natureza_do_controle,
            relacao_com_o_risco: @relacao_com_o_risco %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_modal_processo.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" data-controller="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" inert>
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "shared/form_processo", processo: @processo %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_modal_risco.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="exampleModal" data-controller="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" inert>
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "shared/form_risco", processo: @processo, risco: @risco, tipo_de_risco: @tipo_de_risco, associacao_risco: @associacao_risco, dimensoes_risco: @dimensoes_risco, probabilidade: @probabilidade, impacto: @impacto, resposta_sugerida_para_risco: @resposta_sugerida_para_risco %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="max-width: 100vw; height: 80px;">
  <div class="container-fluid">
    <% if !user_signed_in? %>
      <%= image_tag "logo.png", alt: "CGM-RJ", width: 50 %>
    <% end %>

    <div class="collapse navbar-collapse me-4" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto me-5 mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 200px;">
  <%= link_to dashboards_path, class: "navbar-brand d-flex justify-content-center" do %>
    <%= image_tag "logo.png", alt: "CGM-RJ", width: 100 %>
  <% end %>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to "Painel", dashboards_path, class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
    <li>
      <%= link_to "Processos", processos_path, class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
    <li>
      <%= link_to "Riscos", riscos_path, class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
    <li>
      <%= link_to "Controles", controles_path, class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
    <li>
      <%= link_to "Relatórios", gerar_relatorio_path, class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
    <hr>
    <li>
      <%= link_to "Política de Gestão de Riscos da CGM-Rio", "https://controladoria.prefeitura.rio/politica-de-gestao-de-riscos-da-cgm-rio/", :target => "_blank", class: "btn btn-outline-primary border-0", style: "width: 100%;" %>
    </li>
  </ul>
</div>