config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "processos#home"

  resources :dashboards, only: ['index']

  get 'relatorios/gerar_relatorio', to: 'relatorios#gerar_relatorio', as: :gerar_relatorio

  resources :relatorios, only: [] do
    collection do
      get :setores
      get :processos
    end
  end

  resources :processos do
    resources :riscos, only: ['new', 'create']
  end

  resources :riscos, only: ['index', 'show', 'edit', 'update', 'destroy'] do
		resources :controles, only: ['new', 'create']
  end

  resources :controles, only: ['index', 'show', 'edit', 'update', 'destroy']
end

app/models/risco.rb
class Risco < ApplicationRecord
  belongs_to :processo
  has_many :controles, dependent: :destroy

  validates :nome, presence: true

  def valor_existe_procedimento_controle()
    self.existe_procedimento_de_controle ? "Sim" : "Não"
  end

  def valor_controle_eficaz()
    self.controle_eficaz ? "Sim" : "Não"
  end

  def valor_controle_proporcional()
    self.controle_proporcional ? "Sim" : "Não"
  end

  def valor_controle_proporcional()
    self.controle_proporcional ? "Sim" : "Não"
  end

  def valor_controle_razoavel()
    self.controle_razoavel ? "Sim" : "Não"
  end

  def valor_controle_adequado()
    self.controle_adequado ? "Sim" : "Não"
  end

  def valor_relacao_com_LGPD
    self.relacao_com_LGPD ? "Sim" : "Não"
  end

  # def formatar_data_identificacao
  #   self.data_identificacao.strftime("%d/%m/%Y")
  # end

  # def formatar_data_maxima_para_implantacao_dos_controles_propostos
  #   self.data_maxima_para_implantacao_dos_controles_propostos.strftime("%d/%m/%Y")
  # end
end

app/controllers/riscos_controller.rb
class RiscosController < ApplicationController
  before_action :set_processo, only: [:new, :create]
  before_action :set_risco, only: [:show, :edit, :update, :destroy]
  before_action :set_dropboxes_values_form, only: [:new, :edit]

  def index
    @riscos = Risco.all
  end

  def show
    @processo = @risco.processo
    @controles = @risco.controles
  end

  def new
    @risco = Risco.new
  end

  def create
    @risco = @processo.riscos.build(risco_params)
    if @risco.save
      redirect_to risco_path(@risco), notice: 'Risco cadastrado com sucesso'
    else
      render :new, alert: 'Erro ao cadastrar risco', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @risco.update(risco_params)
      redirect_to risco_path(@risco), notice: 'Risco atualizado com sucesso'
    else
      render :edit, notice: 'Erro ao atualizar risco', status: :unprocessable_entity
    end
  end

  def destroy
    @processo = @risco.processo
    if @risco.destroy
      redirect_to processo_path(@processo), notice: 'Risco excluído com sucesso'
    else
      redirect_to @risco, alert: 'Erro ao excluir risco', status: :unprocessable_entity
    end
  end

  private

  def risco_params
    params.require(:risco).permit(:nome, :data_identificacao, :tipo_de_risco, :associacao_risco, :causas, :consequencias, :dimensoes_risco, :probabilidade,
                                  :justificativa_pr, :impacto, :justificativa_imp, :risco_inerente, :existe_procedimento_de_controle, :descricao_do_controle_existente,
                                  :controle_eficaz, :controle_proporcional, :controle_razoavel, :controle_adequado, :fator_de_avaliacao_controles, :risco_residual,
                                  :resposta_sugerida_para_risco, :data_maxima_para_implantacao_dos_controles_propostos, :relacao_com_LGPD)
  end

  def set_processo
    @processo = Processo.find(params[:processo_id])
  end

  def set_risco
    @risco = Risco.find(params[:id])
  end

  def set_dropboxes_values_form
    @tipo_de_risco = ['Suporte', 'Operacional']
    @associacao_risco = ['Projeto', 'Processo', 'Objetivo Estratégico']
    @dimensoes_risco = ['Estratégico', 'Operacional', 'Imagem', 'Conformidade', 'Sancionatório', 'Orçamentário', 'Integridade', 'Privacidade']
    @probabilidade = ['Muito Baixa', 'Baixa', 'Média', 'Alta', 'Muito Alta']
    @impacto = ['Muito Baixo', 'Baixo', 'Médio', 'Alto', 'Crítico']
    @resposta_sugerida_para_risco = ['Evitar', 'Eliminar', 'Reduzir', 'Compartilhar', 'Potencializar', 'Aceitar']
  end
end

app/helpers/riscos_helper.rb
module RiscosHelper
end

app/views/riscos/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "shared/modal_risco" %>
<% end %>

app/views/riscos/index.html.erb
<div class="container" style="height: 100vh; width: auto;">
  <div>
    <% if @riscos.exists? %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Nome do Risco</th>
            <th scope="col">Associado ao Processo</th>
            <th scope="col">Órgão</th>
            <th scope="col">Data de identificação</th>
            <th scope="col">Tipo de Risco</th>
            <th scope="col">Associação do Risco</th>
            <th scope="col">Dimensões do Risco</th>
            <th scope="col">Probabilidade</th>
            <th scope="col">Impacto</th>
          </tr>
        </thead>
        <tbody>
          <% @riscos.each do |risco| %>
            <tr>
              <td><%= link_to risco.nome, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.processo.nome, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.processo.orgao, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.data_identificacao, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.tipo_de_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.dimensoes_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.associacao_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.probabilidade, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td><%= link_to risco.impacto, risco_path(risco), class: "text-dark text-decoration-none" %></td>
              <td>
                <%= link_to edit_risco_path(risco), data: { controller:"show-form", action: "click->show-form#showForm" }, remote: true do %>
                  <i class="fa-solid fa-pencil"></i>
                <% end %>
              </td>
              <td>
                <%= link_to risco_path(risco), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este processo?" } do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h1>Nenhum risco cadastrado</h1>
    <% end %>
  </div>
</div>

app/views/riscos/new.html.erb
<div class="container d-flex justify-content-center my-5">
  <div class="col-8">
    <div class="border rounded p-5">
      <h1 class="d-flex justify-content-center mb-5">Adicione um novo risco</h1>
      <%= render "shared/form_risco", processo: @processo, risco: @risco, tipo_de_risco: @tipo_de_risco, associacao_risco: @associacao_risco, dimensoes_risco: @dimensoes_risco, probabilidade: @probabilidade, impacto: @impacto, resposta_sugerida_para_risco: @resposta_sugerida_para_risco %>
    </div>
  </div>
</div>

app/views/riscos/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "shared/modal_risco" %>
<% end %>

app/views/riscos/show.html.erb
<div class="d-flex">
  <div class="container">
    <div class="my-4">
      <h1><%=@risco.nome %></h1>
      <p><strong>Data de Identificação: </strong><%= @risco.data_identificacao %></p>
      <p><strong>Tipo de Risco: </strong><%= @risco.tipo_de_risco %></p>
      <p><strong>Associação do Risco: </strong><%= @risco.associacao_risco %></p>
      <p><strong>Causas: </strong><%= @risco.causas %></p>
      <p><strong>Consequências: </strong><%= @risco.consequencias %></p>
      <p><strong>Dimensões do Risco: </strong><%= @risco.dimensoes_risco %></p>
      <p><strong>Probabilidade/Frequência (Fr): </strong><%= @risco.probabilidade %></p>
      <p><strong>Justificativa da Probabilidade: </strong><%= @risco.justificativa_pr %></p>
      <p><strong>Impacto (I): </strong><%= @risco.impacto %></p>
      <p><strong>Justificativa do Impacto: </strong><%= @risco.justificativa_imp %></p>
      <p><strong>Risco Inerente (I x Fr): </strong><%= @risco.risco_inerente %></p>
      <p><strong>Existe Procedimento de Controle? </strong><%= @risco.valor_existe_procedimento_controle %></p>
      <p><strong>Descrição do Controle Existente: </strong><%= @risco.descricao_do_controle_existente %></p>
      <p><strong>O Controle é Eficaz? </strong><%= @risco.valor_controle_eficaz %></p>
      <p><strong>O Controle é Proporcional? </strong><%= @risco.valor_controle_proporcional %></p>
      <p><strong>O Controle é Razoável? </strong><%= @risco.valor_controle_razoavel %></p>
      <p><strong>O Controle é Adequado? </strong><%= @risco.valor_controle_adequado %></p>
      <p><strong>Fator de Avaliação dos Controles (FAC): </strong><%= @risco.fator_de_avaliacao_controles %></p>
      <p><strong>Risco Residual (RI x FAC): </strong><%= @risco.risco_residual %></p>
      <p><strong>Resposta Sugerida ao Risco: </strong><%= @risco.resposta_sugerida_para_risco %></p>
      <p><strong>Data Máxima para Implantação dos Controles: </strong><%= @risco.data_maxima_para_implantacao_dos_controles_propostos %></p>
      <p><strong>Tem Relação com a LGPD? </strong><%= @risco.valor_relacao_com_LGPD %></p>

      <div class="d-flex justify-content-between align-items-center" style="width: 600px;">
        <p><%= link_to "Editar", edit_risco_path(@risco), data: { controller:"show-form", action: "click->show-form#showForm" }, class: "btn btn-primary", style: "width: 100px;" %></p>
        <p><%= link_to "Voltar", processo_path(@processo), class: "btn btn-primary", style: "width: 100px;" %></p>
        <p>
          <%= link_to "Excluir", risco_path(@risco),
            data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este risco?" },
            class: "btn btn-outline-danger",
            style: "width: 100px;" %>
        </p>
        <p>
          <%= link_to new_risco_controle_path(@risco),
            data: { controller:"show-form", action: "click->show-form#showForm" },
            class: "d-flex justify-content-center align-items-center btn btn-outline-secondary border rounded-pill",
            style: "width: 250px; height: 40px;",
            remote: true do %>
            <span>Adicionar Novo Controle
              <i class="fa-solid fa-plus"></i>
            </span>
          <% end %>
        </p>
      </div>
      <hr>
      <div>
        <% if @controles.exists? %>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Nome do Controle</th>
                <th scope="col">Controle Novo ou Modificado?</th>
                <th scope="col">Tipo do Controle</th>
                <th scope="col">Natureza do Controle</th>
                <th scope="col">Relação com o Risco</th>
                <th scope="col">Responsável pela Ação</th>
                <th scope="col">Data Prevista de Início</th>
                <th scope="col">Data Prevista de Conclusão</th>
                <th scope="col">Data Real de Conclusão</th>
                <th scope="col">Órgãos Setores Envolvidos</th>
                <th scope="col">Análise EGR</th>
              </tr>
            </thead>
            <tbody>
              <% @controles.each do |controle| %>
                <tr>
                  <td><%= link_to controle.nome, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.novo_ou_modificado, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.tipo_do_controle, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.natureza_do_controle, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.relacao_com_o_risco, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.responsavel_pela_acao, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.data_prevista_de_inicio, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.data_prevista_de_conclusao, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.data_real_de_conclusao, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.orgaos_setores_envolvidos, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td><%= link_to controle.analise_EGR, controle_path(controle), class: "text-dark text-decoration-none" %></td>
                  <td>
                    <%= link_to edit_controle_path(controle), data: { controller:"show-form", action: "click->show-form#showForm" }, remote: true do %>
                      <i class="fa-solid fa-pencil"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to controle_path(controle), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este processo?" } do %>
                      <i class="fa-solid fa-trash-can"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <h1>Nenhum Controle Cadastrado</h1>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= turbo_frame_tag "bootstrap_modal" %>