config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "processos#home"

  resources :dashboards, only: ['index']

  get 'relatorios/gerar_relatorio', to: 'relatorios#gerar_relatorio', as: :gerar_relatorio

  resources :relatorios, only: [] do
    collection do
      get :setores
      get :processos
    end
  end

  resources :processos do
    resources :riscos, only: ['new', 'create']
  end

  resources :riscos, only: ['index', 'show', 'edit', 'update', 'destroy'] do
		resources :controles, only: ['new', 'create']
  end

  resources :controles, only: ['index', 'show', 'edit', 'update', 'destroy']
end

app/models/processo.rb
class Processo < ApplicationRecord
  has_many :riscos, dependent: :destroy
  has_many :controles, through: :riscos

  validates :nome, :orgao, :setor, presence: true
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  before_action :set_processo, only: [:show, :edit, :update, :destroy]
  before_action :set_dropboxes_values_form, only: [:show, :new, :edit]

  def home
    @resource = User.new
    @resource_name = :user
    @devise_mapping = Devise.mappings[:user]

    redirect_to dashboards_path if user_signed_in?
  end

  def index
    @processos = Processo.all
  end

  def show
    @riscos = @processo.riscos
  end

  def new
    @processo = Processo.new
  end

  def create
    @processo = Processo.new(processo_params)
    if @processo.save
      redirect_to processo_path(@processo), notice: "Processo criado com sucesso!"
    else
      render :new, alert: "Erro ao criar processo!", status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @processo.update(processo_params)
      redirect_to processo_path(@processo), notice: "Processo atualizado com sucesso!"
    else
      render :edit, alert: "Erro ao atualizar processo!", status: :unprocessable_entity
    end
  end

  def destroy
    if @processo.destroy
      redirect_to processos_path, notice: "Processo excluído com sucesso!"
    else
      redirect_to processo_path(@processo), alert: "Erro ao excluir processo!", status: :unprocessable_entity
    end
  end

  private

  def processo_params
    params.require(:processo).permit(:nome, :orgao, :setor, :gestor_processo, :servidor_responsavel, :objetivo_estrategico, :embasamento_legal, :sistemas_utilizados, :partes_interessadas)
  end

  def set_processo
    @processo = Processo.find(params[:id])
  end

  def set_dropboxes_values_form
    @tipo_de_risco = ['Suporte', 'Operacional']
    @associacao_risco = ['Projeto', 'Processo', 'Objetivo Estratégico']
    @dimensoes_risco = ['Estratégico', 'Operacional', 'Imagem', 'Conformidade', 'Sancionatório', 'Orçamentário', 'Integridade', 'Privacidade']
    @probabilidade = ['Muito Baixa', 'Baixa', 'Média', 'Alta', 'Muito Alta']
    @impacto = ['Muito Baixo', 'Baixo', 'Médio', 'Alto', 'Crítico']
    @resposta_sugerida_para_risco = ['Evitar', 'Eliminar', 'Reduzir', 'Compartilhar', 'Potencializar', 'Aceitar']
  end
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/views/processos/edit.html.erb
<div class="container d-flex justify-content-center my-5">
  <div class="col-8">
    <div class="border rounded p-5">
      <h1 class="d-flex justify-content-center mb-5">Edite os dados do processo</h1>
      <%= render "shared/form_processo", processo: @processo %>
    </div>
  </div>
</div>

app/views/processos/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "shared/modal_processo" %>
<% end %>

app/views/processos/home.html.erb
<div class="container d-flex justify-content-around mt-4">
  <div class="col-8">
    <h1>Bem-vindos à plataforma de gerenciamento de riscos da
    Controladoria-Geral do Município do Rio de Janeiro</h1>
    <div class="mt-3">
      <p>
        Esta plataforma foi desenvolvida com base na Política de
        Gerenciamento de Riscos da Controladoria-Geral do Município do Rio de Janeiro.
      </p>
      <p>
        A Política de Gestão de Riscos - PGR tem como finalidade identificar, corrigir e
        tratar os riscos existentes nos processos de trabalho estratégicos adotados no âmbito
        do órgão, agindo para a diminuição dos impactos que possam afetar, direta ou indiretamente,
        o alcance dos objetivos traçados no seu planejamento estratégico.
      </p>
    </div>
  </div>

  <div class="d-flex" style="height: 350px;">
    <div class="vr"></div>
  </div>

  <div class="col-2">
    <div class="mx-auto" style="width: 200px;">
      <h2>Log in</h2>
      <%= form_for(@resource, as: @resource_name, url: session_path(@resource_name)) do |f| %>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "current-password" %>
        </div>
        <% if @devise_mapping.rememberable? %>
          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        <% end %>
        <div class="actions">
          <%= f.submit "Log in" %>
        </div>
      <% end %>

      <%= link_to "Ainda não possui cadastro? Cadastre-se aqui!", new_user_registration_path %>
    </div>
  </div>
</div>

app/views/processos/index.html.erb
<div style="height: 100vh; width: auto;">
  <div class="d-flex justify-content-between my-4">
    <h1>Processos</h1>
    <div class="d-flex align-items-center">
      <%= link_to new_processo_path,
        class: "d-flex justify-content-center align-items-center btn btn-outline-secondary border rounded-pill",
        style: "width: 200px; height: 40px;",
        data: { controller:"show-form", action: "click->show-form#showForm" },
        remote: true do %>
        <span>Adicionar Processo
          <i class="fa-solid fa-plus"></i>
        </span>
      <% end %>
    </div>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Órgão</th>
        <th scope="col">Setor Responsável</th>
        <th scope="col">Nome do Processo</th>
        <th scope="col">Gestor do Processo</th>
        <%#<th scope="col">Servidor Responsável</th>
        <th scope="col">Objetivo Estratégico</th>
        <th scope="col">Embasamento Legal</th>
        <th scope="col">Sistemas Utilizados</th>
        <th scope="col">Partes Interessadas</th>%>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @processos.each do |processo| %>
        <tr>
          <td><%= link_to processo.orgao, processo_path(processo), class: "text-dark text-decoration-none" %></td>
          <td><%= link_to processo.setor, processo_path(processo), class: "text-dark text-decoration-none" %></td>
          <td><%= link_to processo.nome, processo_path(processo), class: "text-dark text-decoration-none" %></td>
          <td><%= link_to processo.gestor_processo, processo_path(processo), class: "text-dark text-decoration-none" %></td>
          <%#<td><%= link_to processo.servidor_responsavel, processo_path(processo), class: "text-dark text-decoration-none" %><%#</td>
          <%#<td><%= link_to processo.objetivo_estrategico, processo_path(processo), class: "text-dark text-decoration-none" %><%#</td>
          <%#<td><%= link_to processo.embasamento_legal, processo_path(processo), class: "text-dark text-decoration-none" %><%#</td>
          <%#<td><%= link_to processo.sistemas_utilizados, processo_path(processo), class: "text-dark text-decoration-none" %><%#</td>
          <%#<td><%= link_to processo.partes_interessadas, processo_path(processo), class: "text-dark text-decoration-none" %><%#</td>%>
          <td data-controller="modal-processo">
            <%= link_to edit_processo_path(processo),
              data: { controller:"show-form", action: "click->show-form#showForm" },
              remote: true do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= link_to processo_path(processo), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este processo?" } do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= turbo_frame_tag "bootstrap_modal" %>

app/views/processos/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="container d-flex justify-content-center my-5">
    <div class="col-8">
      <div class="border rounded p-5">
        <h1 class="d-flex justify-content-center mb-5">Adicione um novo processo</h1>
        <%= render "shared/form_processo", processo: @processo %>
      </div>
    </div>
  </div>
<% end %>

app/views/processos/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "shared/modal_processo" %>
<% end %>

app/views/processos/show.html.erb
<div class="d-flex">
  <div style="height: 100vh; width: auto;">
    <div class="container">
      <div class="mt-4">
        <h1><%= @processo.nome %></h1>
        <hr>
        <p><strong>Órgão: </strong><%= @processo.orgao %></p>
        <p><strong>Setor: </strong><%= @processo.setor %></p>
        <p><strong>Gestor do Processo: </strong><%= @processo.gestor_processo %></p>
        <p><strong>Servidor Responsável: </strong><%= @processo.servidor_responsavel %></p>
        <p><strong>Objetivo Estratégico Associado: </strong><%= @processo.objetivo_estrategico %></p>
        <p><strong>Embasamento Legal: </strong><%= @processo.embasamento_legal %></p>
        <p><strong>Sistemas Utilizados: </strong><%= @processo.sistemas_utilizados %></p>
        <p><strong>Partes Interessadas: </strong><%= @processo.partes_interessadas %></p>
        <div class="d-flex justify-content-between align-items-center" style="width: 600px;">
          <p><%= link_to "Editar", edit_processo_path(@processo), data: { controller:"show-form", action: "click->show-form#showForm" }, class: "btn btn-primary", style: "width: 100px;" %></p>
          <p><%= link_to "Voltar", processos_path, class: "btn btn-primary", style: "width: 100px;" %></p>
          <p>
            <%= link_to "Excluir", processo_path(@processo),
            data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este processo?" },
            class: "btn btn-outline-danger",
            style: "width: 100px;" %>
          </p>
          <p>
            <%= link_to new_processo_risco_path(@processo), data: { controller:"show-form", action: "click->show-form#showForm" },
              class: "d-flex justify-content-center align-items-center btn btn-outline-secondary border rounded-pill",
              style: "width: 250px; height: 40px;",
              remote: true do %>
              <span>Adicionar Novo Risco
                <i class="fa-solid fa-plus"></i>
              </span>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <hr>
    <div>
      <% if @riscos.exists? %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">Nome do Risco</th>
              <th scope="col">Data de identificação</th>
              <th scope="col">Tipo de Risco</th>
              <th scope="col">Associação do Risco</th>
              <th scope="col">Dimensões do Risco</th>
              <th scope="col">Probabilidade</th>
              <th scope="col">Impacto</th>
            </tr>
          </thead>
          <tbody>
            <% @riscos.each do |risco| %>
              <tr>
                <td><%= link_to risco.nome, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.data_identificacao, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.tipo_de_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.dimensoes_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.associacao_risco, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.probabilidade, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td><%= link_to risco.impacto, risco_path(risco), class: "text-dark text-decoration-none" %></td>
                <td>
                  <%= link_to edit_risco_path(risco), data: { controller:"show-form", action: "click->show-form#showForm" }, remote: true do %>
                    <i class="fa-solid fa-pencil"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to risco_path(risco), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir este processo?" } do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h1>Nenhum risco cadastrado</h1>
      <% end %>
    </div>
  </div>
</div>
<%= turbo_frame_tag "bootstrap_modal" %>